---
title: "A poly-time test for difference terms in idempotent varieties"
author:
- "William DeMeo [&lt;williamdemeo@gmail.com&gt;](mailto:williamdemeo@gmail.com)"
- "joint work with<br> 
  Ralph Freese & Matt Valeriote"
date: "`r format(Sys.time(), '%d %B %Y')`"
tags: [difference term, Mal'cev conditions]
abstract: |
  This is the abstract.

  It consists of two paragraphs.
output:
  revealjs::revealjs_presentation:
    center: false
    theme: night
    transition: fade
    self_contained: false
    incremental: true
    keep_md: true
    highlight: pygments
    reveal_plugins: ["notes", "chalkboard", "zoom"]
    reveal_options:
      center: false
      progress: true
      slideNumber: true
---

## The Problem

- Can we efficiently decide whether a given finite algebra $\mathbf{A}$ generates
  a variety with a difference term?

- We give a positive answer in the idempotent case and describe 
  an algorithm for constructing difference terms. 

---

## Definitions

- A  <a style="color:#e7ad52">*difference term*</a> for $\mathcal V$ is a term $d$ satisfying,
  for all $\mathbf A = \langle A, \dots \rangle \in \mathcal V$ and all $a, b \in A$, <br> <br>
  $$d(a,a,b) = b \quad \text{ and } \quad
  d(a,b,b) \mathrel{[\theta, \theta]} a.$$
  <br>
- Here $\theta$ is an arbitrary congruence containing $(a,b)$
  and $[\cdot, \cdot]$ is the <a style="color:#e7ad52">*commutator*</a>.

<aside class="notes"> When the relations above hold we call $d^{\mathbf{A}}$
a **difference term operation** for $\mathbf{A}$.
</aside>

---


## Problem Statement


+ Is there a poly-time algorithm that takes in a finite
  idempotent algebra $\mathbf{A}$ and decides 
  whether $\mathbb{V}(\mathbf{A})$ has a diff term?

+ Kearnes (*J Alg 1995*) <br>
 <a style="color:#e7ad52">$\mathbb{V}(\mathbf{A})$ has a diff term</a> $\Leftrightarrow$
<a style="color:#e7ad52">$\mathbb{V}(\mathbf{A})$ has Taylor term and no typ-2 tails</a>

---

## Reduced Problem Statement

+ <a style="color:#e7ad52">$\mathbb{V}(\mathbf{A})$ has a diff term</a> 
$\Leftrightarrow$ <a style="color:#e7ad52"> $\mathbb{V}(\mathbf{A})$ omits 1's and type-2
  tails</a>

+ Omitting 1's is poly-time decidable by Valeriote's subtype theorem.

+ <a style="color:#e7ad52">**Problem**</a> <br>
  Is there a poly-time algorithm that takes in a finite 
  idempotent algebra $\mathbf{A}$ and decides whether 
  $\mathbb{V}(\mathbf{A})$ has non-empty type-2 tails?

---

## A Related Problem

+ **Theorem** (Freese, Valeriote *IJAC 2009*)<br>
  There is a poly-time algorithm that takes in a finite
  idempotent algebra $\mathbf{A}$ and decides whether $\mathbb{V}(\mathbf{A})$ is 
  <a style="color:#e7ad52">*congruence-modular*</a>.

+ *Congruence-modularity* is characterized by omitting 1's, 5's, and tails.

+ Strategy:
  - No 1's and no 5's can be decided by Valeriote's subtype theorem.
  - Freese and Valeriote proved that if there is a tail in 
    $\mathbb{V}(\mathbf{A})$, then there is a tail "near the bottom."


---

The following result will be useful.

**Theorem.** Let $\mathbf{A}$ be a finite idempotent algebra and $T$ an order ideal in the
lattice of types. Then $\mathbb{V}(\mathbf{A})$ omits $T$ if and only if $\mathsf{S}(\mathbf{A})$ does.

<aside class="notes"> In particular, $\mathbb{V}(\mathbf{A})$ omits 1 and 2 if and only if $\mathsf{S}(\mathbf{A})$ omits 1 and 2.</aside>


---


- Freese and Valeriote prove a sequence of lemmas to establish that, 
  if $\mathbf{A}$ is finite and idempotent, and if
  $\mathcal V = \mathbb{V}(\mathbf{A})$ omits types 1 and 5, 
  then to test for the existence of tails
  in $\mathcal V$ it suffices to look for them 
  in the 3-generated subalgebras of $\mathbf{A}^2$.

---

- Throughout, we let $[n]$ denote the set $\{0,1,\dots, n-1\}$ and 
  we let $\mathcal S$ be a finite set of finite, similar, idempotent algebras, 
  closed under the taking of subalgebras, such that 
  $\mathcal V = \mathbb{V}(\mathcal S)$ omits type-1 (but may include type-\mathcal typ).

- If there is a finite algebra in $\mathcal V$ having a type-2 minimal 
  set with a tail, then, by standard tame congruence theory, there
  is such an algebra which is a subalgebra of a product 
  of elements in $\mathcal S$. 

---

- Suppose that some finite algebra $\mathbf{B}$ in $\mathcal V$ has a prime 
  quotient of type~2 whose minimal sets have non-empty tails.

- We show that there is a 3-generated subalgebra of the
  product of two members of $\mathcal S$ with this property.

- Since $\mathcal S$ is closed under the taking of subalgebras,
  we may assume that the algebra $\mathbf{B}$ from the previous paragraph is a subdirect
  product of a finite number of members of $\mathcal S$. 

- Choose $n$ minimal such that for some $\mathbf{A}_0$, $\mathbf{A}_1$, 
  $\dots$, $\mathbf{A}_{n-1}$ in $\mathcal S$, there is a subdirect
  product $\mathbf{B} \sdp \prod_{[n]} \mathbf{A}_i$
  that has a prime quotient of type~2 whose minimal sets have
  non-empty tails.
  
- Under the assumption that $n > 1$ we will prove that $n = 2$.

---

- For this $n$, select the $\mathbf{A}_i$ and $\mathbf{B}$ so that $|B|$ is as small as possible.

- Let $\alpha \prec \beta$ be a prime quotient of $\mathbf{B}$ 
  of type~2 such that its minimal sets have
  non-empty tails, and choose $\beta$ minimal with this property.

- By HM, this implies $\beta$ is join 
  irreducible and $\alpha$ is its unique subcover.
  Let $U$ be an $(\alpha, \beta)$-minimal set. 

---

## Lemma 3.1

If $0$, $1 \in U$ such that $(0,1) \in \beta - \alpha$ and
$t$ be a member of the tail of $U$. Then $\beta$ is the 
congruence of $\mathbf{B}$
generated by the pair $(0,1)$ and $\mathbf{B}$ is generated 
by $\{0, 1, t\}$.

---

For $i \leq n$, let $\rho_i$ 
denote the kernel of the projection of $\mathbf{B}$ onto $\mathbf{A}_i$,
so $\mathbf{B} \cong \mathbf{A}_i/\rho_i$.
For a subset $\sigma \subseteq [n]$, define

$\rho_\sigma := \bigwedge_{j\in \sigma} \rho_j.$

Consequently,

$\rho_{[n]} = \bigwedge_{j\in [n]}\rho_j = 0_{B}$

By minimality of $n$ we know that the intersection of any  proper subset of the
$\rho_i$, $1 \leq i \leq n$ is strictly above $0_B$.  Thus,
$0_B < \rho_\sigma < 1_B$ for all 
$\emptyset \subset \sigma\subset [n]$
(by $\subset$ we mean \emph{proper} subset).

---

## Lemma 3.2
  For every proper nonempty subset $\sigma \subset [n]$,
  either $\beta \leq \rho_\sigma$ or $\alpha \join \rho_\sigma = 1_B$.

## Near Permutability Lemma

For every proper nonempty subset $\sigma \subset [n]$,
for all $v\in B$, and for all $c\in \body(U)$, we have
$(v,c) \in \beta \circ \rho_\sigma \cap \rho_\sigma \circ \beta$.

## Lemma 3.3

1. There exists $0\leq i< n $ such that $\alpha \join \rho_i = 1_B$

2. There exists $i$ such that $\alpha \join \rho_i < 1_B$.

---

## Theorem 3.4

Let $\mathcal V$ be the variety generated by some finite set $\mathcal S$ of finite,
idempotent algebras that is closed under taking subalgebras. If $\mathcal V$
omits type~1 and some finite member of $\mathcal V$ has a prime quotient 
of type~2 whose minimal sets have non-empty tails, then there is some
3-generated algebra $\alg B$ with this property that belongs to $\mathcal S$ or 
is a subdirect product of two algebras from $\mathcal S$. 



